compose:
  zookeeper:
    net: host
    image: bobrik/zookeeper
    environment:
      - ZK_CONFIG=tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      - ZK_ID=1
  mesos-master:
    net: host
    image: mesosphere/mesos-master:0.26.1-2.0.19.ubuntu1404
    environment:
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=docker-compose
      - MESOS_REGISTRY=replicated_log  # in_memory
  mesos-slave:
    net: host
    image: mesosphere/mesos-slave:0.26.1-2.0.19.ubuntu1404
    environment:
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      # MESOS_HOSTNAME: SLAVE_IP_GOES_HERE
      - MESOS_PORT=5051
      - MESOS_RESOURCES=ports(*):[11000-11999]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true


build:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t lensacom/satyr .

  test:
    image: lensa/mesos-python:0.26.0-py2.7-python-2.7
    net: host
    environment:
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
    commands:
      - python setup.py test
