compose:
  zookeeper:
    net: host
    image: bobrik/zookeeper
    environment:
      - ZK_CONFIG=tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      - ZK_ID=1
  mesos-master:
    net: host
    image: mesosphere/mesos-master:0.28.1
    environment:
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=docker-compose
      - MESOS_REGISTRY=in_memory
  mesos-slave:
    net: host
    image: mesosphere/mesos-slave:0.28.1
    environment:
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_PORT=5051
      - MESOS_RESOURCES=cpus(*):1.5;ports(*):[11000-11999]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true


build:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t lensa/satyr .

  test:
    image: lensa/satyr
    net: host
    environment:
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - ZOOKEEPER_HOST=127.0.0.1:2181
    commands:
      - python setup.py test


publish:
  pypi:
    repository: https://pypi.python.org/pypi
    username: $$PYPI_USERNAME
    password: $$PYPI_PASSWORD
    distributions:
      - sdist
    when:
      event: [tag]

  docker:
    username: $$DOCKERHUB_USERNAME
    password: $$DOCKERHUB_PASSWORD
    email: $$DOCKERHUB_EMAIL
    repo: lensa/satyr
    file: Dockerfile
    tag:
      - $$TAG
      - latest
    when:
      event: [tag]

  docker:
    username: $$DOCKERHUB_USERNAME
    password: $$DOCKERHUB_PASSWORD
    email: $$DOCKERHUB_EMAIL
    repo: lensa/satyr
    file: Dockerfile
    tag:
      - master
    when:
      branch: master
